version: '3.7'

# local
services:
  db:
    image: postgres:14.6
    command:
      ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    container_name: gohango-psql
    ports:
      - 65435:5432
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "gohango"
